modLoader="javafml"
loaderVersion="[47,)"
license="Attribution-NonCommercial-ShareAlike 4.0 International"
[[mods]]
modId="cyberwareplus"
version="1.1"
displayName="Cyberware Plus"
authors="msdoggirl"
description="Addon to Cyberware: Reforged that adds overhauled aesthetics with high mod compatibility."
[[dependencies.cyberwareplus]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cyberwareplus]]
modId="dglib"
mandatory=true
versionRange="1.0_alpha"
ordering="NONE"
side="BOTH"

[[mixins]]
config="mixins.cyberwareplus.json"

